[project]
name = "air"
version = "0.20.0"
description = "The new web framework that breathes fresh air into Python web development. Built with FastAPI, Starlette, and Pydantic."
authors = [
    { name = "Audrey M. Roy Greenfeld", email = "audrey@feldroy.com" },
    { name = "Daniel Roy Greenfeld", email = "daniel@feldroy.com" }
]
dependencies = [
    "fastapi>=0.116.1",
    "Jinja2>=3.1.6",
    "python-multipart>=0.0.20",
]

readme = "README.md"
requires-python = ">= 3.10"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
"air" = "air.cli:app"

[project.optional-dependencies]
# Make `air[standard]` install FastAPI’s own “standard” extras, available with: uv pip install "air[standard]".
standard = [
    # Re-install FastAPI with its “standard” extra.
    "fastapi[standard]>=0.116.1",
]
dev = [
    # Justfile tasks
    "rust-just>=1.42.3",
]
test = [
    # Measure how much of the code is covered by tests
    "coverage>=7.8.2",
    # For the test client
    "httpx>=0.28.1",
    # Used with debugging
    "ipdb>=0.13.13",
    # Test runner
    "pytest>=8.4.0",
    # Linting and formatting
    "ruff>=0.11.13",
    # Justfile tasks
    "rust-just>=1.42.3",
    # for checking types
    "ty>=0.0.1a16",
    # Types for the markdown library
    "types-Markdown>=3.8.0",
    # Lets you run full example apps
    "uvicorn>=0.34.0",
    # Fix common misspellings in text files
    "codespell>=2.4.1",
]
docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-autorefs>=1.4.2",
]

[project.urls]
homepage = "https://github.com/feldroy/air"
bugs = "https://github.com/feldroy/air/issues"

[tool.mypy]
exclude = "^build/"

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.uv]
package = true

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv.sources]
air = { workspace = true }

[tool.ruff]
line-length = 120
target-version = "py313"
indent-width = 4

[tool.ruff.format]
indent-style = "space"   # match EditorConfig
line-ending = "lf"       # enforce LF newlines
quote-style = "double"   # keep quotes in sync with flake8-quotes

[tool.ruff.lint]
# E/W = pycodestyle; F = pyflakes; Q = flake8-quotes; UP = pyupgrade
# I = isort; N = pep8-naming; B = bugbear; T201/T203 = flake8-print
select = ["E", "F", "W", "Q", "UP", "I", "N", "B", "T201", "T203"]
extend-select = ["RUF100", "C90", "D"]  # RUF100=unused-noqa, C90=McCabe, D=pydocstyle
ignore = [
    "D100", # ignore missing docstring in module
    "D102", # ignore missing docstring in public method
    "D104", # ignore missing docstring in public package
    "D105", # ignore missing docstring in magic methods
    "D107", # ignore missing docstring in __init__ methods
]

[tool.ruff.lint.isort]
combine-as-imports = true     # group aliases coming from the same module
force-wrap-aliases = true     # keep the multi-line, parenthesised layout

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.lint.mccabe]
max-complexity = 10  # set the C901 threshold explicitly

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*,*.svg,*.lock,*.css,*.yaml'
check-hidden = true
# Ignore "formatting" like **L**anguage
ignore-regex = '\*\*[A-Z]\*\*[a-z]+\b'
ignore-words-list = 'asend,aci'
