[project]
name = "db"
version = "0.0.0"
dependencies = [
    "greenlet>=3.2.4", # Dependency for SQLAlchemy to run async
    "sqlmodel>=0.0.24", # Bridge between SQLAlchemy and Pydantic
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
